clusterGroup:
  name: prod

  namespaces:
    vault:
    external-secrets:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    redhat-ods-operator:
      operatorGroup: true
      targetNamespaces: []
    openshift-storage:
      operatorGroup: true
      targetNamespaces:
        - openshift-storage

  sharedValueFiles:
    - /overrides/values-{{ $.Values.global.device }}.yaml

  subscriptions:
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: stable-3.x
    lvms:
      name: lvms-operator
      namespace: openshift-storage

  applications:
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*

    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*

    pattern-secrets:
      name: pattern-secrets
      namespace: ai-quickstart-rag-sno-prod
      path: charts/pattern-secrets

    data-science-cluster:
      name: data-science-cluster
      namespace: ai-quickstart-rag-sno-prod
      path: charts/dsc

    lvms:
      name: lvms
      namespace: openshift-storage
      path: charts/lvms

    image-registry:
      name: image-registry
      namespace: openshift-image-registry
      path: charts/image-registry

    bento-box-links:
      name: bento-box-links
      namespace: ai-quickstart-rag-sno-prod
      path: charts/bento-box-links

    rag-quickstart:
      name: rag-quickstart
      namespace: ai-quickstart-rag-sno-prod
      repoURL: https://github.com/rh-ai-quickstart/RAG
      chartVersion: main
      path: deploy/helm/rag
      extraValueFiles:
        - /overrides/rag-quickstart.yaml
      ignoreDifferences:
        - group: datasciencepipelinesapplications.opendatahub.io
          kind: DataSciencePipelinesApplication
          jsonPointers:
            - /spec
        - group: kubeflow.org
          kind: Notebook
          jsonPointers:
            - /spec
            - /metadata/annotations
            - /metadata/labels
        - group: route.openshift.io
          kind: Route
          jsonPointers:
            - /spec/host
            - /spec/alternateBackends

  imperative:
    jobs:
      - name: configure-registry-pull-secret
        playbook: ansible/playbooks/configure-registry-pull-secret.yml
        timeout: 300
